env:
  global:
  - 'FTP_HOST=[FTP_HOST]'
  - 'FTP_USER=[FTP_USER]'
  - 'FTP_PASS=[FTP_PASS]'

language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - sudo apt-get install -y jq nasm
addons:
  apt:
    update: true

after_success:
  - cp packages/blog/_config.sample.yml packages/blog/_config.yml
  - sed -i "s/FTP_HOST/${FTP_HOST}/" packages/blog/_config.yml
  - sed -i "s/FTP_USER/${FTP_USER}/" packages/blog/_config.yml
  - sed -i "s/FTP_PASS/${FTP_PASS}/" packages/blog/_config.yml
  - make publish -C packages/blog
  on:
    branch: release
