language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - sudo apt-get install -y jq nasm
  - npm i -g add $(grep -vE "^\s*#" requirements/npm  | tr "\\n" " ")

addons:
  apt:
    update: true

deploy:
  - provider: script
    script: bash scripts/deploy.sh staging
    on:
      branch: develop

  - provider: script
    script: bash scripts/deploy.sh production
    on:
      branch: master
